version: '3.8'

services:
  web:
    build: .
    command: python url_server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - song_storage:/app/mpthrees
    env_file:
      - .dockerenv
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: python worker.py
    volumes:
      - .:/app
      - song_storage:/app/mpthrees
    env_file:
      - .dockerenv
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  song_storage:
